// 
// Decompiled by Procyon v0.5.36
// 

package org.l2j.gameserver.data.database.data;

import org.l2j.gameserver.data.database.announce.AnnouncementType;
import org.l2j.commons.database.annotation.Table;
import org.l2j.gameserver.data.database.announce.Announce;

@Table(value = "announcements", autoGeneratedProperty = "id")
public class AnnounceData implements Announce
{
    private int id;
    private AnnouncementType type;
    private long initial;
    private long delay;
    private int repeat;
    private String author;
    private String content;
    
    public AnnounceData() {
    }
    
    public AnnounceData(final AnnouncementType type, final String content, final String author, final long initDelay, final long delay, final int repeat) {
        this.type = type;
        this.content = content;
        this.author = author;
        this.initial = initDelay;
        this.delay = delay;
        this.repeat = repeat;
    }
    
    @Override
    public int getId() {
        return this.id;
    }
    
    public void setId(final int id) {
        this.id = id;
    }
    
    @Override
    public AnnouncementType getType() {
        return this.type;
    }
    
    @Override
    public void setType(final AnnouncementType type) {
        this.type = type;
    }
    
    public long getInitial() {
        return this.initial;
    }
    
    public void setInitial(final long initial) {
        this.initial = initial;
    }
    
    public long getDelay() {
        return this.delay;
    }
    
    public void setDelay(final long delay) {
        this.delay = delay;
    }
    
    public int getRepeat() {
        return this.repeat;
    }
    
    public void setRepeat(final int repeat) {
        this.repeat = repeat;
    }
    
    @Override
    public String getAuthor() {
        return this.author;
    }
    
    @Override
    public void setAuthor(final String author) {
        this.author = author;
    }
    
    @Override
    public String getContent() {
        return this.content;
    }
    
    @Override
    public void setContent(final String content) {
        this.content = content;
    }
    
    @Override
    public boolean isValid() {
        return true;
    }
    
    @Override
    public boolean canBeStored() {
        return true;
    }
}
